### ISSUE TITLE
Access error when writing updated plugin

### ISSUE THREAD

**Issue by rshackleton** [SDKE13/ConvertNPCVisualReplacerToSkyPatcher#2]
Error when trying to convert this mod - https://www.nexusmods.com/skyrimspecialedition/mods/54422

```
Back up original file:> Done
Saving mod:> Save error, can not continue.
System.Private.CoreLib
The process cannot access the file 'E:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\Modpocalypse NPCs (v1) SSE.esp' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.IO.Abstractions.FileStreamFactory.New(String path, FileMode mode, FileAccess access)
   at Mutagen.Bethesda.Skyrim.SkyrimModBinaryTranslationMixIn.WriteToBinary(ISkyrimModGetter item, FilePath path, BinaryWriteParameters param, GroupMask importMask)
   at ConvertNPCVisualReplacerToSkyPatcher.Program.ConvertToSkyPatcher(IPatcherState`2 state, String ModToConvert, String ModToConvertPath) in C:\...\ConvertNPCVisualReplacerToSkyPatcher\Program.cs:line 203
```

**Comment by SDKE13** [comment]
Uncheck mod in mod organizer
