### ISSUE TITLE
Error when saving plugin "Record was out of bounds for the given record compaction settings"

### ISSUE THREAD

**Issue by rshackleton** [SDKE13/ConvertNPCVisualReplacerToSkyPatcher#3]
Error when trying to convert this mod - https://www.nexusmods.com/skyrimspecialedition/mods/109529

```
Converting to Skypatch: CS_Visions_N1.esp
Path: E:\Games\SSE Mods\MO2\mods\ColdSun's Visions - NPCs AIO

Elenwen : 013269:Skyrim.esm --> 00ACA3:CS_Visions_N1.esp
ElisifTheFair : 01326A:Skyrim.esm --> 00ACA4:CS_Visions_N1.esp
Endarie : 01326F:Skyrim.esm --> 00ACA5:CS_Visions_N1.esp
Freir : 013277:Skyrim.esm --> 00ACA6:CS_Visions_N1.esp
VittoriaVici : 01327A:Skyrim.esm --> 00ACA7:CS_Visions_N1.esp
Illdi : 013289:Skyrim.esm --> 00ACA8:CS_Visions_N1.esp
Lisette : 013297:Skyrim.esm --> 00ACA9:CS_Visions_N1.esp
Rikke : 0132A1:Skyrim.esm --> 00ACAA:CS_Visions_N1.esp
SilanaPetreia : 0132A5:Skyrim.esm --> 00ACAB:CS_Visions_N1.esp
SybilleStentor : 0132AA:Skyrim.esm --> 00ACAC:CS_Visions_N1.esp
Taarie : 0132AB:Skyrim.esm --> 00ACAD:CS_Visions_N1.esp
Anuriel : 013349:Skyrim.esm --> 00ACAE:CS_Visions_N1.esp
ConstanceMichel : 013350:Skyrim.esm --> 00ACAF:CS_Visions_N1.esp
Haelga : 01335F:Skyrim.esm --> 00ACB0:CS_Visions_N1.esp
Ingun : 013364:Skyrim.esm --> 00ACB1:CS_Visions_N1.esp
Laila : 013366:Skyrim.esm --> 00ACB2:CS_Visions_N1.esp
Maven : 01336A:Skyrim.esm --> 00ACB3:CS_Visions_N1.esp
Mjoll : 01336B:Skyrim.esm --> 00ACB4:CS_Visions_N1.esp
Svana : 01337C:Skyrim.esm --> 00ACB5:CS_Visions_N1.esp
Faleen : 013397:Skyrim.esm --> 00ACB6:CS_Visions_N1.esp
Hroki : 01339E:Skyrim.esm --> 00ACB7:CS_Visions_N1.esp
Orla : 0133B0:Skyrim.esm --> 00ACB8:CS_Visions_N1.esp
Senna : 0133B7:Skyrim.esm --> 00ACB9:CS_Visions_N1.esp
Sigrid : 013476:Skyrim.esm --> 00ACBA:CS_Visions_N1.esp
Delphine : 013478:Skyrim.esm --> 00ACBB:CS_Visions_N1.esp
CamillaValerius : 01347B:Skyrim.esm --> 00ACBC:CS_Visions_N1.esp
Gerdur : 01347C:Skyrim.esm --> 00ACBD:CS_Visions_N1.esp
Alva : 0135E6:Skyrim.esm --> 00ACBE:CS_Visions_N1.esp
IdgrodTheYounger : 0135EC:Skyrim.esm --> 00ACBF:CS_Visions_N1.esp
Karita : 01361A:Skyrim.esm --> 00ACC0:CS_Visions_N1.esp
Narri : 013654:Skyrim.esm --> 00ACC1:CS_Visions_N1.esp
Annekke : 013666:Skyrim.esm --> 00ACC2:CS_Visions_N1.esp
Gilfre : 01367A:Skyrim.esm --> 00ACC3:CS_Visions_N1.esp
Hert : 01367C:Skyrim.esm --> 00ACC4:CS_Visions_N1.esp
Lynly : 0136BC:Skyrim.esm --> 00ACC5:CS_Visions_N1.esp
Fastred : 0136BF:Skyrim.esm --> 00ACC6:CS_Visions_N1.esp
Grelka : 0136C5:Skyrim.esm --> 00ACC7:CS_Visions_N1.esp
CarlottaValentia : 013B99:Skyrim.esm --> 00ACC8:CS_Visions_N1.esp
OlfinaGrayMane : 013B9B:Skyrim.esm --> 00ACC9:CS_Visions_N1.esp
Saadia : 013BA2:Skyrim.esm --> 00ACCA:CS_Visions_N1.esp
Hulda : 013BA3:Skyrim.esm --> 00ACCB:CS_Visions_N1.esp
Arcadia : 013BA4:Skyrim.esm --> 00ACCC:CS_Visions_N1.esp
DanicaPureSpring : 013BA5:Skyrim.esm --> 00ACCD:CS_Visions_N1.esp
Ysolda : 013BAB:Skyrim.esm --> 00ACCE:CS_Visions_N1.esp
Irileth : 013BB8:Skyrim.esm --> 00ACCF:CS_Visions_N1.esp
AdrianneAvenicci : 013BB9:Skyrim.esm --> 00ACD0:CS_Visions_N1.esp
Muiri : 01406B:Skyrim.esm --> 00ACD1:CS_Visions_N1.esp
Adelaisa : 01411D:Skyrim.esm --> 00ACD2:CS_Visions_N1.esp
Eola : 01990F:Skyrim.esm --> 00ACD3:CS_Visions_N1.esp
Borgakh : 019959:Skyrim.esm --> 00ACD4:CS_Visions_N1.esp
Wylandriah : 019DEF:Skyrim.esm --> 00ACD5:CS_Visions_N1.esp
Ugor : 019E1A:Skyrim.esm --> 00ACD6:CS_Visions_N1.esp
AelaTheHuntress : 01A696:Skyrim.esm --> 00ACD7:CS_Visions_N1.esp
Ria : 01A6D7:Skyrim.esm --> 00ACD8:CS_Visions_N1.esp
NjadaStonearm : 01A6D9:Skyrim.esm --> 00ACD9:CS_Visions_N1.esp
Karliah : 01B07F:Skyrim.esm --> 00ACDA:CS_Visions_N1.esp
Astrid : 01BDB4:Skyrim.esm --> 00ACDB:CS_Visions_N1.esp
Gabriella : 01BDB8:Skyrim.esm --> 00ACDC:CS_Visions_N1.esp
Birna : 01C187:Skyrim.esm --> 00ACDD:CS_Visions_N1.esp
BrelynaMaryon : 01C196:Skyrim.esm --> 00ACDE:CS_Visions_N1.esp
Faralda : 01C197:Skyrim.esm --> 00ACDF:CS_Visions_N1.esp
Nirya : 01C19B:Skyrim.esm --> 00ACE0:CS_Visions_N1.esp
MirabelleErvine : 01C1A0:Skyrim.esm --> 00ACE1:CS_Visions_N1.esp
Vex : 01CD90:Skyrim.esm --> 00ACE2:CS_Visions_N1.esp
DA01Aranea : 028AD0:Skyrim.esm --> 00ACE3:CS_Visions_N1.esp
dunDarklightIllia : 048C2F:Skyrim.esm --> 00ACE4:CS_Visions_N1.esp
TembaWideArm : 0658D2:Skyrim.esm --> 00ACE5:CS_Visions_N1.esp
Uthgerd : 0918E2:Skyrim.esm --> 00ACE6:CS_Visions_N1.esp
HousecarlWhiterun : 0A2C8E:Skyrim.esm --> 00ACE7:CS_Visions_N1.esp
HousecarlSolitude : 0A2C8F:Skyrim.esm --> 00ACE8:CS_Visions_N1.esp
HousecarlRiften : 0A2C91:Skyrim.esm --> 00ACE9:CS_Visions_N1.esp
Tonilia : 0B8827:Skyrim.esm --> 00ACEA:CS_Visions_N1.esp
HirelingJenassa : 0B9982:Skyrim.esm --> 00ACEB:CS_Visions_N1.esp
Sapphire : 0C19A3:Skyrim.esm --> 00ACEC:CS_Visions_N1.esp
Sylgja : 0C3A3F:Skyrim.esm --> 00ACED:CS_Visions_N1.esp
dunAngiREF : 0CAB2F:Skyrim.esm --> 00ACEE:CS_Visions_N1.esp
DLC1Serana : 002B6C:Dawnguard.esm --> 00ACEF:CS_Visions_N1.esp
DLC1FuraBloodmouth : 003363:Dawnguard.esm --> 00ACF0:CS_Visions_N1.esp
DLC1Hestla : 003365:Dawnguard.esm --> 00ACF1:CS_Visions_N1.esp
DLC1SorineJurard : 00336B:Dawnguard.esm --> 00ACF2:CS_Visions_N1.esp
DLC1Valerica : 003B8B:Dawnguard.esm --> 00ACF3:CS_Visions_N1.esp
DLC1DawnguardExterior01 : 010DE5:Dawnguard.esm --> 00ACF4:CS_Visions_N1.esp
DLC1DawnguardExterior02 : 010DE6:Dawnguard.esm --> 00ACF5:CS_Visions_N1.esp
DLC1Modhna : 011E5E:Dawnguard.esm --> 00ACF6:CS_Visions_N1.esp
DLC1Ingjard : 01541B:Dawnguard.esm --> 00ACF7:CS_Visions_N1.esp
DLC1Beleval : 01541C:Dawnguard.esm --> 00ACF8:CS_Visions_N1.esp
BYOHHousecarlFalkreath : 005215:HearthFires.esm --> 00ACF9:CS_Visions_N1.esp
DLC2Frea : 017934:Dragonborn.esm --> 00ACFA:CS_Visions_N1.esp
DLC2RRMiloreIenth : 0182A1:Dragonborn.esm --> 00ACFB:CS_Visions_N1.esp
DLC2SVMorwen : 018FA9:Dragonborn.esm --> 00ACFC:CS_Visions_N1.esp
DLC2SVFanariStrongVoice : 018FC5:Dragonborn.esm --> 00ACFD:CS_Visions_N1.esp
DLC2dunFrostmoonHjordis : 01F9C4:Dragonborn.esm --> 00ACFE:CS_Visions_N1.esp
DLC2dunFrostmoonRakel : 01F9C5:Dragonborn.esm --> 00ACFF:CS_Visions_N1.esp
Back up original file:> Done
Saving mod:> Save error, can not continue.
Mutagen.Bethesda.Core
Record was out of bounds for the given record compaction settings
   at Mutagen.Bethesda.Plugins.Analysis.DI.RecordCompactionCompatibilityDetector.ThrowIfIncompatible(IModGetter mod, RangeUInt32 range, IMajorRecordGetter rec)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.<>c__DisplayClass31_0.<AddFormIDCompactionLogic>b__0(IMajorRecordGetter maj)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.RunProcessorsOnMajorRecord(IMajorRecordGetter maj)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.RunProcessors(IModGetter mod)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.WriteHeader(BinaryWriteParameters param, MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.SkyrimModCommon.WriteParallel(ISkyrimModGetter item, MutagenWriter writer, BinaryWriteParameters param, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.SkyrimModBinaryWriteTranslation.Write(MutagenWriter writer, ISkyrimModGetter item, ModKey modKey, GroupMask importMask, BinaryWriteParameters param)
   at Mutagen.Bethesda.Skyrim.SkyrimModBinaryTranslationMixIn.WriteToBinary(ISkyrimModGetter item, FilePath path, BinaryWriteParameters param, GroupMask importMask)
   at ConvertNPCVisualReplacerToSkyPatcher.Program.ConvertToSkyPatcher(IPatcherState`2 state, String ModToConvert, String ModToConvertPath) in C:\Users\rshac\AppData\Local\Temp\Synthesis\gqnh5lln.sfw\Git\4mcq00a0.djk\Runner\ConvertNPCVisualReplacerToSkyPatcher\Program.cs:line 203
Finished patch.
```

**Comment by SDKE13** [comment]
I'll look into it.

**Comment by SDKE13** [comment]
Are you using the latest code?  I made some fixes.

**Comment by SDKE13** [comment]
This mod is esl flagged and the next record pointer is pointing an index outside of esl record size.  You can remove the esl flag and it should save or if you want to go the advanced route renumber formids from 800.  Renumbering form ids will break all patches but save a slot.  If you want to use to esp as a visual replacer only there is a lot of fluff you can nuke.
![image](https://github.com/user-attachments/assets/388b0cd8-b53c-497b-a5c7-e62a2275b829)

**Comment by SDKE13** [comment]
ESL's limited FExxx800 to FExxxFFF range
